# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Zipf_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1139, 759)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1097, 642))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.radioButtonPython = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButtonPython.setGeometry(QtCore.QRect(20, 30, 174, 23))
        self.radioButtonPython.setObjectName("radioButtonPython")
        self.plainTextEditPrevio = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainTextEditPrevio.setGeometry(QtCore.QRect(10, 100, 471, 31))
        self.plainTextEditPrevio.setPlainText("")
        self.plainTextEditPrevio.setObjectName("plainTextEditPrevio")
        self.pushButtonBrowse = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButtonBrowse.setGeometry(QtCore.QRect(500, 100, 89, 25))
        self.pushButtonBrowse.setObjectName("pushButtonBrowse")
        self.pushButtonHist = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButtonHist.setGeometry(QtCore.QRect(260, 140, 181, 25))
        self.pushButtonHist.setObjectName("pushButtonHist")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(20, 0, 241, 21))
        self.label_3.setObjectName("label_3")
        self.label_resTrain = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_resTrain.setGeometry(QtCore.QRect(40, 360, 501, 21))
        self.label_resTrain.setText("")
        self.label_resTrain.setObjectName("label_resTrain")
        self.radioButtonJava = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButtonJava.setGeometry(QtCore.QRect(110, 30, 174, 23))
        self.radioButtonJava.setObjectName("radioButtonJava")
        self.radioButtonC = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButtonC.setEnabled(True)
        self.radioButtonC.setGeometry(QtCore.QRect(180, 30, 174, 23))
        self.radioButtonC.setChecked(True)
        self.radioButtonC.setObjectName("radioButtonC")
        self.hist = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hist.setGeometry(QtCore.QRect(10, 190, 771, 441))
        self.hist.setText("")
        self.hist.setObjectName("hist")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 241, 21))
        self.label_4.setObjectName("label_4")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.hist_2 = QtWidgets.QLabel(self.tab)
        self.hist_2.setGeometry(QtCore.QRect(10, 10, 1091, 581))
        self.hist_2.setText("")
        self.hist_2.setObjectName("hist_2")
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ley de Zipf en lenguajes de programación"))
        self.radioButtonPython.setText(_translate("MainWindow", "Python"))
        self.pushButtonBrowse.setText(_translate("MainWindow", "Browse"))
        self.pushButtonHist.setText(_translate("MainWindow", "Generar histograma"))
        self.label_3.setText(_translate("MainWindow", "Lenguaje de programación"))
        self.radioButtonJava.setText(_translate("MainWindow", "Java"))
        self.radioButtonC.setText(_translate("MainWindow", "C/C++"))
        self.label_4.setText(_translate("MainWindow", "Ruta del archivo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Ley de potencias"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Gráfico"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
